--**************************************************************************
--   Copyright (C) 2005 by George Shapovalov  --
--   george@gentoo.org  --
--                                                                        --
--   This program is free software; you can redistribute it and/or modify --
--   it under the terms of the GNU Library General Public License as      --
--   published by the Free Software Foundation; either version 2 of the   --
--   License, or (at your option) any later version.                      --
--                                                                        --
--   This program is distributed in the hope that it will be useful,      --
--   but WITHOUT ANY WARRANTY; without even the implied warranty of       --
--   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the        --
--   GNU General Public License for more details.                         --
--                                                                        --
--   You should have received a copy of the GNU Library General Public    --
--   License along with this program; if not, write to the                --
--   Free Software Foundation, Inc.,                                      --
--   59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.            --
--**************************************************************************

separate (ABF.Header)
function  Empty_GapFree_ABFFileHeader return ABFFileHeader is

	GFHeader : ABFFileHeader := (
		lFileSignature       => ABF_NATIVESIGNATURE,
		fFileVersionNumber   => ABF_CURRENTVERSION,
		nOperationMode       => ABF_GAPFREEFILE,
		lActualAcqLength     => 0,
		nNumPointsIgnored    => 0,
		lActualEpisodes      => 0,
		lFileStartDate       => 20051114,
		lFileStartTime       => 0000,
		lStopwatchTime       => 0,
		fHeaderVersionNumber => ABF_CURRENTVERSION,
		nFileType            => ABF_ABFFILE,
		nMSBinFormat         => 0,
		--  GROUP #2 - File Structure (78 bytes)
		lDataSectionPtr       => ABFFileHeader'Size / ABF_BLOCKSIZE,
		lTagSectionPtr        => 0,
		lNumTagEntries        => 0,
		lScopeConfigPtr       => 0,
		lNumScopes            => 0,
		d_lDACFilePtr         => 0,
		d_lDACFileNumEpisodes => 0,
		sUnused001    => (others => ' '),
		lDeltaArrayPtr        => 0,
		lNumDeltas            => 0,
		lVoiceTagPtr          => 0,
		lVoiceTagEntries      => 0,
		lUnused002            => 0,
		lSynchArrayPtr        => 0,
		lSynchArraySize       => 0,
		nDataFormat           => 0,
		nSimultaneousScan     => 0,
		lStatisticsConfigPtr  => 0,
		lAnnotationSectionPtr => 0,
		lNumAnnotations       => 0,
		sUnused003    => (others => ' '),
	--  GROUP #3 - Trial hierarchy information (82 bytes)
		channel_count_acquired   => 1,
		nADCNumChannels          => 1,
		fADCSampleInterval       => 100.0,
		fADCSecondSampleInterval => 0.0,
		fSynchTimeUnit           => 0.0,
		fSecondsPerRun           => 0.0,
		lNumSamplesPerEpisode    => 512,
		lPreTriggerSamples       => 16,
		lEpisodesPerRun          => 1,
		lRunsPerTrial            => 0,
		lNumberOfTrials          => 0,
		nAveragingMode           => 0,
		nUndoRunCount            => 0,
		nFirstEpisodeInRun       => 0,
		fTriggerThreshold        => 0.0,
		nTriggerSource           => 0,
		nTriggerAction           => 0,
		nTriggerPolarity         => 0,
		fScopeOutputInterval     => 0.0,
		fEpisodeStartToStart     => 0.0,
		fRunStartToStart         => 0.0,
		fTrialStartToStart       => 0.0,
		lAverageCount            => 0,
		lClockChange             => 0,
		nAutoTriggerStrategy     => 0,
		--  GROUP #4 - Display Parameters (44 bytes)
		nDrawingStrategy        => 0,
		nTiledDisplay           => 0,
		nEraseStrategy          => 1,
		nDataDisplayMode        => ABF_DRAW_LINES,
		lDisplayAverageUpdate   => 0,
		nChannelStatsStrategy   => 0,
		lCalculationPeriod      => 2,
		lSamplesPerTrace        => 16384,
		lStartDisplayNum        => 0,
		lFinishDisplayNum       => 0,
		nMultiColor             => 1,
		nShowPNRawData          => 0,
		fStatisticsPeriod       => 1.0,
		lStatisticsMeasurements => 16#00000005#,
		nStatisticsSaveStrategy => 0,
		--  GROUP #5 - Hardware information (16 bytes)
		fADCRange      => 10.24,
		fDACRange      => 10.24,
		lADCResolution => 32768,
		lDACResolution => 32768,
		--  GROUP #6 Environmental Information (118 bytes)
		nExperimentType          => ABF_SIMPLEACQUISITION,
		d_nAutosampleEnable      => 0,
		d_nAutosampleADCNum      => 0,
		d_nAutosampleInstrument  => 0,
		d_fAutosampleAdditGain   => 0.0,
		d_fAutosampleFilter      => 0.0,
		d_fAutosampleMembraneCap => 0.0,
		nManualInfoStrategy      => 0,
		fCellID1                 => 0.0,
		fCellID2                 => 0.0,
		fCellID3                 => 0.0,
		sCreatorInfo   => (others => ' '),
		d_sFileComment => (others => ' '),
		nFileStartMillisecs      => 0,
		nCommentsEnable          => 0,
		sUnused003a    => (others => ' '),
		--  GROUP #7 - Multi-channel information (1044 = (160 + 384 + 488 + 12) bytes)
		nADCPtoLChannelMap => (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15),
		nADCSamplingSeq    => (others => ABF_UNUSED_CHANNEL),
		sADCChannelName    =>
			("AI #0     ", "AI #1     ", "AI #2     ", "AI #3     ",
			 "AI #4     ", "AI #5     ", "AI #6     ", "AI #7     ",
			 "AI #8     ", "AI #9     ", "AI #10    ", "AI #11    ",
			 "AI #12    ", "AI #13    ", "AI #14    ", "AI #15    "),
		sADCUnits          => (others => ('p', 'A', others => ' ')),
		fADCProgrammableGain     => (others => 1.0),
		fADCDisplayAmplification => (others => 1.0),
		fADCDisplayOffset        => (others => 0.0),
		fInstrumentScaleFactor   => (others => 1.0),
		fInstrumentOffset        => (others => 0.0),
		fSignalGain              => (others => 1.0),
		fSignalOffset            => (others => 0.0),
		fSignalLowpassFilter     => (others => ABF_FILTERDISABLED),
		fSignalHighpassFilter    => (others => ABF_FILTERDISABLED),
		sDACChannelName  => ("AO #0     ", "AO #1     ", "AO #2     ", "AO #3     "),
		sDACChannelUnits => (others => "mV      "),
		fDACScaleFactor  => (others => 20.0),
		fDACHoldingLevel => (others =>  0.0),
		nSignalType      => 0,
		sUnused004       => (others => ' '),
		--  GROUP #8 - Synchronous timer outputs (14 bytes)
		nOUTEnable        => 0,
		nSampleNumberOUT1 => 0,
		nSampleNumberOUT2 => 0,
		nFirstEpisodeOUT  => 0,
		nLastEpisodeOUT   => 0,
		nPulseSamplesOUT1 => 0,
		nPulseSamplesOUT2 => 0,
		--  GROUP #9 - Epoch Waveform and Pulses (184 bytes)
		nDigitalEnable       => 0,
		A_nWaveformSource    => 0,
		nActiveDACChannel    => 0,
		A_nInterEpisodeLevel => 0,
		A_nEpochType         => (others => 0),
		A_fEpochInitLevel    => (others => 0.0),
		A_fEpochLevelInc     => (others => 0.0),
		A_nEpochInitDuration => (others => 0),
		A_nEpochDurationInc  => (others => 0),
		nDigitalHolding      => 0,
		nDigitalInterEpisode => 0,
		nDigitalValue        => (others => 0),
		sUnavailable1608     => (others => ' '),
			--  was float fWaveformOffset,
		nDigitalDACChannel => 0,
		sUnused005         => (others => ' '),
		--  GROUP #10 - DAC Output File (98 bytes)
		d_fDACFileScale      => 1.0,
		d_fDACFileOffset     => 0.0,
		sUnused006           => (others => ' '),
		d_nDACFileEpisodeNum => 0,
		d_nDACFileADCNum     => 0,
		d_sDACFilePath       => (others => ' '),
		--  GROUP #11 - Conditioning pulse train (44 bytes)
		d_nConditEnable     => 0,
		d_nConditChannel    => 0,
		d_lConditNumPulses  => 0,
		d_fBaselineDuration => 0.0,
		d_fBaselineLevel    => 0.0,
		d_fStepDuration     => 0.0,
		d_fStepLevel        => 0.0,
		d_fPostTrainPeriod  => 0.0,
		d_fPostTrainLevel   => 0.0,
		sUnused007          => (others => ' '),
		--  GROUP #12 - Variable parameter user list ( 82 bytes)
		d_nParamToVary    => 0,
		d_sParamValueList => (others => ' '),
		--  GROUP #13 - Autopeak measurement (36 bytes)
		nAutopeakEnable     => 0,
		nAutopeakPolarity   => 0,
		nAutopeakADCNum     => 0,
		nAutopeakSearchMode => 0,
		lAutopeakStart      => 0,
		lAutopeakEnd        => 0,
		nAutopeakSmoothing  => 0,
		nAutopeakBaseline   => 0,
		nAutopeakAverage    => 0,
		sUnavailable1866    => (others => ' '),
			--  Was nAutopeakSaveStrategy, use nStatisticsSaveStrategy
		lAutopeakBaselineStart => 0,
		lAutopeakBaselineEnd   => 0,
		lAutopeakMeasurements  => 0,
		--  GROUP #14 - Channel Arithmetic (52 bytes)
		nArithmeticEnable     => 0,
		fArithmeticUpperLimit => 0.0,
		fArithmeticLowerLimit => 0.0,
		nArithmeticADCNumA    => 0,
		nArithmeticADCNumB    => 0,
		fArithmeticK1         => 0.0,
		fArithmeticK2         => 0.0,
		fArithmeticK3         => 0.0,
		fArithmeticK4         => 0.0,
		sArithmeticOperator   => " +",
		sArithmeticUnits      => (others => ' '),
		fArithmeticK5         => 0.0,
		fArithmeticK6         => 0.0,
		nArithmeticExpression => 0,
		sUnused008            => (others => ' '),
		--  GROUP #15 - On-line subtraction (34 bytes)
		d_nPNEnable       => 0,
		nPNPosition       => 0,
		d_nPNPolarity     => 0,
		nPNNumPulses      => 0,
		d_nPNADCNum       => 0,
		d_fPNHoldingLevel => 0.0,
		fPNSettlingTime   => 0.0,
		fPNInterpulse     => 0.0,
		sUnused009        => (others => ' '),
		--  GROUP #16 - Unused space at end of header block (82 bytes)
		d_nListEnable              => 0,
		nBellEnable                => (others => 0),
		nBellLocation              => (others => 0),
		nBellRepetitions           => (others => 0),
		nLevelHysteresis           => DEFAULT_LEVEL_HYSTERESIS,
		lTimeHysteresis            => DEFAULT_TIME_HYSTERESIS,
		nAllowExternalTags         => 0,
		nLowpassFilterType         => (others => ' '),
		nHighpassFilterType        => (others => ' '),
		nAverageAlgorithm          => 0,
		fAverageWeighting          => 0.1,
		nUndoPromptStrategy        => 0,
		nTrialTriggerSource        => ABF_TRIALTRIGGER_NONE,
		nStatisticsDisplayStrategy => 0,
		nExternalTagType           => ABF_EXTERNALTAG,
		lHeaderSize                => ABF_HEADERSIZE,
		dFileDuration              => 0.0,
		nStatisticsClearStrategy   => 0,

		--  Extra parameters in v1.6
		--  GROUP #2 - File Structure (8 * 2 = 16)
		lDACFilePtr         => (others => 0),
		lDACFileNumEpisodes => (others => 0),
		--  EXTENDED GROUP #3 - Trial Hierarchy
		fFirstRunDelay => 0.0,
		sUnused010     => (others => ' '),
		--  GROUP #7 - Multi-channel information (62 bytes)
		fDACCalibrationFactor => (others => 1.0),
		fDACCalibrationOffset => (others => 0.0),
		sUnused011            => (others => ' '),
		--  // GROUP #17 - Trains parameters (160 bytes)
		lEpochPulsePeriod => (others => (others => 0)),
		lEpochPulseWidth  => (others => (others => 0)),
		--  GROUP #9 - Epoch Waveform and Pulses ( 412 bytes)
		nWaveformEnable          => (others => 0),
		nWaveformSource          => (others => 0),
		nInterEpisodeLevel       => (others => 0),
		nEpochType               => (others => (others => 0)),
		fEpochInitLevel          => (others => (others => 0.0)),
		fEpochLevelInc           => (others => (others => 0.0)),
		lEpochInitDuration       => (others => (others => 0)),
		lEpochDurationInc        => (others => (others => 0)),
		nDigitalTrainValue       => (others => 0),
		nDigitalTrainActiveLogic => 0,
		sUnused012               => (others => ' '),
		--  GROUP #10 - DAC Output File (552 bytes)
		fDACFileScale      => (others => 1.0),
		fDACFileOffset     => (others => 0.0),
		lDACFileEpisodeNum => (others => 0),
		nDACFileADCNum     => (others => 0),
		sDACFilePath       => (others => (others => ' ')),
		sUnused013         => (others => ' '),
		--  GROUP #11 - Presweep (conditioning) pulse train (100 bytes)
		nConditEnable     => (others => 0),
		lConditNumPulses  => (others => 0),
		fBaselineDuration => (others => 0.0),
		fBaselineLevel    => (others => 0.0),
		fStepDuration     => (others => 0.0),
		fStepLevel        => (others => 0.0),
		fPostTrainPeriod  => (others => 0.0),
		fPostTrainLevel   => (others => 0.0),
		sUnused014        => (others => ' '),
		--  GROUP #12 - Variable parameter user list (1096 bytes)
		nULEnable         => (others => 0),
		nULParamToVary    => (others => 0),
		sULParamValueList => (others => (others => ' ')),
		nULRepeat         => (others => 0),
		sUnused015        => (others => ' '),
		--  GROUP #15 - On-line subtraction (56 bytes)
		nPNEnable         => (others => 0),
		nPNPolarity       => (others => 0),
		dd_nPNADCNum      => (others => 0),
		fPNHoldingLevel   => (others => 0.0),
		nPNNumADCChannels => (others => 0),
		nPNADCSamplingSeq => (others => (others => ' ')),
		--  GROUP #6 Environmental Information  ( 898 bytes)
		nTelegraphEnable               => (others => 0),
		nTelegraphInstrument           => (others => 0),
		fTelegraphAdditGain            => (others => 0.0),
		fTelegraphFilter               => (others => 0.0),
		fTelegraphMembraneCap          => (others => 0.0),
		nTelegraphMode                 => (others => 0),
		nTelegraphDACScaleFactorEnable => (others => 0),
		sUnused016a                    => (others => ' '),
		nAutoAnalyseEnable             => 0,
		sAutoAnalysisMacroName         => (others => ' '),
		sProtocolPath                  => (others => ' '),
		sFileComment                   => (others => ' '),
		fInstrumentHoldingLevel        => (others => 0.0),
		FileGUID                       => (others => ' '),
		ulFileCRC                      => 0,
		sModifierInfo                  => (others => ' '),
		sUnused6                       => (others => ' '),
		--  // EXTENDED GROUP #13 - Statistics measurements (388 bytes)
		nStatsEnable            => 0,
		nStatsActiveChannels    => 0,
		nStatsSearchRegionFlags => 0,
		nStatsSelectedRegion    => 0,
		d_nStatsSearchMode      => 0,
		nStatsSmoothing         => 0,
		nStatsSmoothingEnable   => 0,
		nStatsBaseline          => 0,
		lStatsBaselineStart     => 0,
		lStatsBaselineEnd       => 0,
		lStatsMeasurements      => (others => 0),
		lStatsStart            => (others => 0),
		lStatsEnd              => (others => 0),
		nRiseBottomPercentile  => (others => 0),
		nRiseTopPercentile     => (others => 0),
		nDecayBottomPercentile => (others => 0),
		nDecayTopPercentile    => (others => 0),
		nStatsChannelPolarity  => (others => 0),
		nStatsSearchMode       => (others => 0),
		sUnused018 => (others => ' '),
		--  // GROUP #18 - Application version data (16 bytes)
		nCreatorMajorVersion   => 0,
		nCreatorMinorVersion   => 0,
		nCreatorBugfixVersion  => 0,
		nCreatorBuildVersion   => 0,
		nModifierMajorVersion  => 0,
		nModifierMinorVersion  => 0,
		nModifierBugfixVersion => 0,
		nModifierBuildVersion  => 0,
		--  // GROUP #19 - LTP protocol (14 bytes)
		nLTPType              => 0,
		nLTPUsageOfDAC        => (others => 0),
		nLTPPresynapticPulses => (others => 0),
		sUnused020            => (others => ' '),
		--  // GROUP #20 - Digidata 132x Trigger out flag. (8 bytes)
		nDD132xTriggerOut => 0,
		sUnused021        => (others => ' '),
		--  // GROUP #21 - Epoch resistance (40 bytes)
		sEpochResistanceSignalName => (others => (others => ' ')),
		nEpochResistanceState      => (others => 0),
		sUnused022                 => (others => ' '),
		--  // GROUP #22 - Alternating episodic mode (58 bytes)
		nAlternateDACOutputState     => 0,
		nAlternateDigitalValue       => (others => 0),
		nAlternateDigitalTrainValue  => (others => 0),
		nAlternateDigitalOutputState => 0,
		sUnused023                   => (others => ' '),
		--  // GROUP #23 - Post-processing actions (210 bytes, including sUnused2048)
		fPostProcessLowpassFilter     => (others => 0.0),
		nPostProcessLowpassFilterType => (others => ' '),

		sUnused2048 => (others => ' ')
	);

  begin
	return GFHeader;
  end Empty_GapFree_ABFFileHeader;
